### PR TITLE
Fix SDK generation under Go 1.26 (bump pulumi-terraform-bridge to v3.130.0)

### PR DESCRIPTION
**Pull request by datarobot-kyrylo-hrymailo**
## Problem

The [Upgrade provider](https://github.com/datarobot-community/pulumi-datarobot/actions/workflows/upgrade-provider.yml) workflow has been failing during `make generate_sdks`. The NodeJS SDK fails to compile:

```
config/vars.ts(5,28): error TS2307: Cannot find module './utilities'
types/index.ts(4,28): error TS2307: Cannot find module './utilities'
types/input.ts(5,25): error TS2307: Cannot find module './types/input'
```

The generated nested files (`config/`, `types/`) imported `./utilities` / `./types/input` instead of `../utilities` / `../types/input`.

## Root cause

Go 1.26 changed `path/filepath.Rel(base, "")` to return `..` instead of `../.` for a one-level base. The pinned `pulumi/pkg v3.160.0` NodeJS codegen `getRelativePath()` did `path.Dir(filepath.Rel(mod.mod, ""))`, which relied on the old behavior — under Go 1.26 it collapses to `.` for nested modules, producing unresolvable imports.

Upstream `terraform-provider-datarobot` v0.10.40+ bumped its module to `go 1.26.4`, so the `pulumi-tfgen-datarobot` binary must build with Go 1.26, which triggers the bug. This is **not** caused by the provider version bump itself — regenerating even the last good release (v0.10.39) under Go 1.26 reproduces it.

Pulumi fixed this in [pulumi/pulumi#21835](https://github.com/pulumi/pulumi/pull/21835) (`filepath.Clean` instead of `path.Dir`), first released in `pulumi/pkg` ~v3.242.0.

## Changes

- **`provider/go.mod`**
  - `pulumi-terraform-bridge/v3` `v3.106.0` → `v3.130.0`
  - `pulumi/pulumi/{pkg,sdk}/v3` `v3.160.0` → `v3.242.0` (contains the fix)
  - `replace terraform-plugin-sdk/v2` → pulumi fork `v2.0.0-20260318212141-5525259d096b`
  - `pulumi-java/pkg v1.8.0` → `pulumi-java v1.26.1` (root module; the `/pkg` submodule was discontinued)
- **`.github/workflows/upgrade-provider.yml`, `upgrade-and-test.yml`**: `target-bridge-version` `v3.106.0` → `v3.130.0` (otherwise the next automated upgrade reverts the bridge)
- Regenerated `schema.json`, `Pulumi.yaml`, and all SDKs (nodejs/python/go/dotnet)

`terraform-provider-datarobot` is intentionally left at v0.10.39 so the existing `upgrade-provider` automation performs the v0.10.41 bump cleanly on its next run.

## Verification

`make generate_sdks` passes under Go 1.26.4 — nodejs (`tsc` clean, imports now `../utilities`), python, go, and dotnet (`Build succeeded, 0 Error(s)`).

---

> [!NOTE]
> **Medium Risk**
> Touches core codegen/toolchain versions that affect all language SDK outputs; risk is mainly build/regression surface rather than runtime provider behavior.
> 
> **Overview**
> Aligns automated provider upgrades with **pulumi-terraform-bridge v3.130.0** (and the newer Pulumi codegen that fixes NodeJS relative imports under Go 1.26) so `make generate_sdks` succeeds again.
> 
> **Workflow defaults** in `upgrade-provider.yml` and `upgrade-and-test.yml` change `target-bridge-version` from `v3.106.0` to `v3.130.0`, preventing the next scheduled upgrade from pinning the old bridge and re-breaking SDK generation.
> 
> Adds **`provider/cmd/pulumi-resource-datarobot/Pulumi.yaml`** as part of regenerated provider metadata for schema-based packaging.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit 3daeda454e41273a1c3bce10aa099b19ffff11b3. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

**Comment by cdevent** [comment]
Superseded by #362, which takes the bridge to **v3.137.0** instead of v3.130.0 — 7 releases further on, verified building end to end.

#362 keeps the two dependency fixes this PR diagnosed:

- `pulumi/pulumi-java/pkg v1.8.0` → root module `pulumi/pulumi-java v1.34.0` (the `/pkg` submodule is discontinued and shadows the root module's `codegen/java` package)
- `terraform-plugin-sdk/v2` replace → the current Pulumi fork

It also removes the `sed` workarounds that #341 added to `build_nodejs`/`build_python` as an interim fix, since the underlying [pulumi/pulumi#21835](https://github.com/pulumi/pulumi/pull/21835) codegen bug is fixed in the newer `pulumi/pkg` — verified against raw codegen output.

Rebasing this branch was the alternative, but it is based on June's `main` with v0.10.39-era SDKs and `main` is now at v0.10.46, so a clean regeneration was less risky than resolving conflicts across every generated SDK file.

Thanks for the root-cause analysis here — the `filepath.Rel` diagnosis is what made #362 straightforward. Closing in favour of that.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
